### PR TITLE
Add m-no as attendee

### LINKED ISSUE #5: m-no participates Github training
- [ ] m-no has willing to participate Github training.
  - [ ] m-no can communicate with other contributors with respects.
  - [ ] Create `m-no.md`.

### PR DESCRIPTION
**Pull request by h-misonou**
- [x] m-no has willing to participate Github training.
- [x] m-no can communicate with other contributors with respects.
- [x] Create `m-no.md`.
  Close: #5

### CODE REVIEW

**Comment by atoato88** [comment]
It's your first PR right?
Thank you for quick response!!

**Comment by atoato88** [comment]
I've checked your change now.
It looks good for me!
Owner will merge this PR, I think.

**Comment by h-misonou** [comment]
Yes, My 1st PR!!!
thanks

**Comment by shu-mutou** [comment]
Thanks!!! ❤️

**Pull request merged**
